# Generated by Django 6.1 on 2026-08-20 10:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the restaurant')),
                ('address', models.CharField(help_text='Full address of the restaurant', max_length=500)),
                ('cuisine_type', models.CharField(help_text='Type of cuisine (e.g., Italian, Chinese, Indian)', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Average customer rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('delivery_time', models.IntegerField(default=30, help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the restaurant is currently accepting orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dish', max_length=200)),
                ('description', models.TextField(help_text='Description of the dish')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the dish', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Image of the dish (optional)', null=True, upload_to='menu_items/')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Whether the dish is vegetarian')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the dish is currently available')),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('side', 'Side Dish')], default='main_course', help_text='Category of the dish', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(help_text='The restaurant this menu item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
