# Generated by Django 5.2.5 on 2026-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Restaurant logo or image', null=True, upload_to='restaurant_logos/')),
                ('hero_image', models.ImageField(blank=True, help_text='Hero image for meal list page', null=True, upload_to='restaurant_heroes/')),
                ('hero_title', models.CharField(blank=True, default='Delicious Meals', help_text='Hero title for meal list page', max_length=200)),
                ('hero_description', models.TextField(blank=True, default='Discover amazing food from top restaurants in your area. Fresh ingredients, great taste, and fast delivery.', help_text='Hero description for meal list page')),
                ('delivery_time', models.CharField(blank=True, default='30-45 minutes', help_text='Estimated delivery time', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Restaurant phone number', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Restaurant email', max_length=254)),
                ('opening_hours', models.CharField(blank=True, default='Mon-Sun: 9:00 AM - 10:00 PM', help_text='Restaurant opening hours', max_length=100)),
                ('overall_rating', models.FloatField(default=0.0, help_text='Overall star rating (0.0 to 5.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
