# Generated by Django 6.1 on 2026-09-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image of the restaurant (optional)', null=True, upload_to='restaurants/'),
        ),
    ]
