# Generated by Django 6.1 on 2026-09-26 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Average rating for this dish (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='How many customers rated this dish (e.g., 1200 for 1.2K+)'),
        ),
    ]
