# Generated by Django 6.1 on 2026-09-29 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_rating_menuitem_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Approximate delivery distance from customer (in km)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
