# Generated by Django 6.1 on 2026-09-20 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(help_text='Razorpay order id (order_xxx) generated by the SDK. Unique because Razorpay never issues duplicates.', max_length=200, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, help_text='Razorpay payment id (pay_xxx). Set only after the user completes payment and the frontend receives the callback.', max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, help_text='Razorpay HMAC signature. Stored for audit/debugging only. NEVER exposed via API responses.', max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the given currency (e.g., 1200.00 INR)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', help_text='ISO currency code. INR for Razorpay by default.', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', help_text='Current state of this payment attempt', max_length=20)),
                ('method', models.CharField(blank=True, help_text='Payment method used (card, upi, netbanking, wallet, etc.). Populated from Razorpay after successful verification.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The order this payment attempt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_288dd3_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
