# Generated by Django 6.1 on 2026-09-28 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', help_text='Home / Office / Other', max_length=10)),
                ('label', models.CharField(help_text="Short user-given name, e.g. 'Mom's place'", max_length=50)),
                ('full_name', models.CharField(help_text='Name of the recipient at this address', max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('line1', models.CharField(help_text='Flat / building / street', max_length=200)),
                ('line2', models.CharField(blank=True, default='', help_text='Area / locality (optional)', max_length=200)),
                ('landmark', models.CharField(blank=True, default='', help_text='Nearby landmark (optional)', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('is_default', models.BooleanField(default=False, help_text="If true, this is the user's preferred delivery address.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
