"""
Payments App Models

This app owns the Razorpay payment flow for orders.

Architecture:
    Order (1)
      │
      │ ForeignKey
      ▼
    Payment (many)   # retry after failure creates a new row

Why ForeignKey and not OneToOne?
    A user might attempt payment multiple times for the same order
    (wrong card, network error, retry after failure). Each attempt
    is its own Payment row. Only the successful one flips the Order
    to 'confirmed'.

Lifecycle of a Payment record:

    1. POST /api/payments/create/
         - Razorpay order created via SDK
         - Payment row created: status='initiated'

    2. Frontend opens Razorpay Checkout, user pays.

    3. POST /api/payments/verify/
         - Signature checked by SDK
         - Success: status='success', razorpay_payment_id + method set
         - Failure: status='failed'

Security notes:
- razorpay_signature is stored for audit/debugging ONLY.
  It is NEVER exposed via API responses.
- razorpay_key_secret is never stored on this model.
  It lives in settings.py and is only used by the SDK.
"""

from django.core.validators import MinValueValidator
from django.db import models


class Payment(models.Model):
    """
    One payment attempt for an Order.

    Multiple Payment rows can exist for the same Order
    (one per attempt). At most one of them should end up
    with status='success'.
    """

    # ------------------------------------------------------------------
    # Status choices
    # ------------------------------------------------------------------
    STATUS_INITIATED = 'initiated'
    STATUS_SUCCESS = 'success'
    STATUS_FAILED = 'failed'

    STATUS_CHOICES = [
        (STATUS_INITIATED, 'Initiated'),
        (STATUS_SUCCESS, 'Success'),
        (STATUS_FAILED, 'Failed'),
    ]

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    order = models.ForeignKey(
        'orders.Order',
        on_delete=models.CASCADE,
        related_name='payments',
        help_text='The order this payment attempt belongs to',
    )

    # ------------------------------------------------------------------
    # Razorpay identifiers
    # ------------------------------------------------------------------
    razorpay_order_id = models.CharField(
        max_length=200,
        unique=True,
        help_text=(
            'Razorpay order id (order_xxx) generated by the SDK. '
            'Unique because Razorpay never issues duplicates.'
        ),
    )

    razorpay_payment_id = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        help_text=(
            'Razorpay payment id (pay_xxx). Set only after the user '
            'completes payment and the frontend receives the callback.'
        ),
    )

    razorpay_signature = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        help_text=(
            'Razorpay HMAC signature. Stored for audit/debugging only. '
            'NEVER exposed via API responses.'
        ),
    )

    # ------------------------------------------------------------------
    # Amount / currency
    # ------------------------------------------------------------------
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0)],
        help_text='Amount in the given currency (e.g., 1200.00 INR)',
    )

    currency = models.CharField(
        max_length=10,
        default='INR',
        help_text='ISO currency code. INR for Razorpay by default.',
    )

    # ------------------------------------------------------------------
    # Status / method
    # ------------------------------------------------------------------
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_INITIATED,
        help_text='Current state of this payment attempt',
    )

    method = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text=(
            'Payment method used (card, upi, netbanking, wallet, etc.). '
            'Populated from Razorpay after successful verification.'
        ),
    )

    # ------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # ------------------------------------------------------------------
    # Meta
    # ------------------------------------------------------------------
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        indexes = [
            # Fast lookups by order when listing a user's payments.
            models.Index(fields=['order', '-created_at']),
            # Fast status-based queries (e.g., find all successes).
            models.Index(fields=['status']),
        ]

    # ------------------------------------------------------------------
    # String representation
    # ------------------------------------------------------------------
    def __str__(self):
        return (
            f"Payment #{self.id} - Order #{self.order_id} - "
            f"{self.status} - {self.amount} {self.currency}"
        )

    # ------------------------------------------------------------------
    # Helper properties
    # ------------------------------------------------------------------
    @property
    def is_successful(self):
        """True if this payment attempt succeeded."""
        return self.status == self.STATUS_SUCCESS

    @property
    def is_failed(self):
        """True if this payment attempt failed."""
        return self.status == self.STATUS_FAILED

    @property
    def is_pending(self):
        """True if this payment has been created but not yet resolved."""
        return self.status == self.STATUS_INITIATED