"""
Django settings for swiggy project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for local development


# Application definition
# These are the Django apps that will be used in our Swiggy clone project.
# Each app handles a specific functionality:
# - users: User authentication (login, logout, register)
# - restaurants: Restaurant and menu item management
# - orders: Order handling and REST API for placing orders

INSTALLED_APPS = [
    'django.contrib.admin',       # Built-in admin panel for managing data
    'django.contrib.auth',        # Authentication system
    'django.contrib.contenttypes',# Content type framework
    'django.contrib.sessions',    # Session management
    'django.contrib.messages',    # Messaging framework
    'django.contrib.staticfiles', # Static file handling

    'corsheaders', # CORS (to prevent connection of backend-frontend)
    
    # Third-party apps
    'rest_framework',             # Django REST Framework for API endpoints
    'rest_framework_simplejwt.token_blacklist', # blacklist Access/refresh tokens while logout
    
    # Local apps (our custom apps)
    'users',                      # User authentication app
    'restaurants',                # Restaurant and menu management app
    'orders',                     # Orders and cart management app
    'cart',                       # cart management app
    'payments'                    # payments management app
]

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',   # This creates temperary session_id in browser without token
    ),
    # Optional: You can add this if you want to require authentication globally,
    # but we will leave it open for now.

    # Django REST Framework Configuration
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow unauthenticated requests (for learning)
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # Token expires in 30 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),      # Refresh token valid for 1 day
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    # CORS (to prevent connection of backend-frontend)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swiggy.urls'

# TEMPLATES configuration tells Django where to find HTML template files
# DIRS: We set this to BASE_DIR / 'templates' so all templates are in a central folder
# APP_DIRS: True means Django will also look for templates inside each app's templates/ folder
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Central templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swiggy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'your_db_name',
        'USER': 'your_db_user',
        'PASSWORD': 'your_db_password',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: Directory where collectstatic will gather all static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_URL and MEDIA_ROOT are for user-uploaded files (like restaurant logos, meal images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type (Django 3.2+)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ============================================================
# RAZORPAY CONFIGURATION (Test Mode)
# ============================================================
# These are TEST keys from the Razorpay dashboard.
# In production, move these to environment variables (.env).
#
# How to get them:
#   Razorpay Dashboard -> Settings -> API Keys -> Generate Test Key
#
# RAZORPAY_KEY_ID     : starts with "rzp_test_"
# RAZORPAY_KEY_SECRET : long alphanumeric string (never share this)

RAZORPAY_KEY_ID = 'rzp_test_XXXXXXXXXXXXXXXX'
RAZORPAY_KEY_SECRET = 'your_razorpay_key_secret_here'

# Backend Frontend Cors connection.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://your-local-ip:3000',  # Replace with your actual local network IP if needed
]

CORS_ALLOW_CREDENTIALS = True
