"""
Django settings for swiggy project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-msb$4$o+lb5zaql++-6bti#916cz*8@p#1k&!!&6q_1d^6&s4a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for local development


# Application definition
# These are the Django apps that will be used in our Swiggy clone project.
# Each app handles a specific functionality:
# - users: User authentication (login, logout, register)
# - restaurants: Restaurant and menu item management
# - orders: Order handling and REST API for placing orders

INSTALLED_APPS = [
    'django.contrib.admin',       # Built-in admin panel for managing data
    'django.contrib.auth',        # Authentication system
    'django.contrib.contenttypes',# Content type framework
    'django.contrib.sessions',    # Session management
    'django.contrib.messages',    # Messaging framework
    'django.contrib.staticfiles', # Static file handling
    
    # Third-party apps
    'rest_framework',             # Django REST Framework for API endpoints
    
    # Local apps (our custom apps)
    'users',                      # User authentication app
    'restaurants',                # Restaurant and menu management app
    'orders',                     # Orders and cart management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swiggy.urls'

# TEMPLATES configuration tells Django where to find HTML template files
# DIRS: We set this to BASE_DIR / 'templates' so all templates are in a central folder
# APP_DIRS: True means Django will also look for templates inside each app's templates/ folder
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Central templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swiggy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASE CONFIGURATION FOR MYSQL
# To use this project:
# 1. Create a MySQL database: CREATE DATABASE swiggy_db;
# 2. Update the DATABASES settings below with your MySQL credentials
# 3. Install PyMySQL (already in requirements.txt)
# 4. Run: python manage.py migrate

# Option 1: MySQL Configuration (Uncomment and fill in your credentials)
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'swiggy_db',          # Your database name
        'USER': 'your_mysql_username', # Your MySQL username
        'PASSWORD': 'your_password',   # Your MySQL password
        'HOST': 'localhost',           # Usually localhost
        'PORT': '3306',                # MySQL default port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
"""

# Option 2: SQLite for quick testing (Default - change to MySQL above for production)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# NOTE: For learning purposes, you can start with SQLite (above).
# When ready to use MySQL, comment out the SQLite block and uncomment the MySQL block above.
# Then update your credentials and run: python manage.py migrate


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: Directory where collectstatic will gather all static files for deployment
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_URL and MEDIA_ROOT are for user-uploaded files (like restaurant logos, meal images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type (Django 3.2+)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Allow unauthenticated requests (for learning)
    ],
}
